# version: '3.8'
services:
  clickhouse_node_01:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse_node_01
    mem_limit: 256m
    ports:
      - '8000:8123'
      - '9000:9000'
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=node1
    networks:
      - ch_network
      
  clickhouse_node_02:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse_node_02
    mem_limit: 256m
    ports:
      - '8001:8123'
      - '9001:9000'
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=node2
    networks:
      - ch_network
      
  clickhouse_node_03:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse_node_03
    mem_limit: 256m
    ports:
      - '8002:8123'
      - '9002:9000'
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=node3
    networks:
      - ch_network
      
  clickhouse_node_04:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse_node_04
    mem_limit: 256m
    ports:
      - '8003:8123'
      - '9003:9000'
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=node4
    networks:
      - ch_network

networks:
  ch_network:
    driver: bridge