# version: '3.8'
services:
  master_clickhouse :
    image: yandex/clickhouse-server 
    container_name: master_clickhouse
    restart: unless-stopped
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=default
    volumes:
      - ${storage_path}/master_clickhouse_log:/var/log/clickhouse-server/ 
    #   - ${storage_path}/master_clickhouse:/etc/clickhouse-server/config.d 
      
  clickhouse_node_01:
    image: yandex/clickhouse-server 
    container_name: clickhouse_node_01
    ports:
      - '8001:8123'
      - '9001:9000'
      - '9181:9181'
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=default
    volumes:
      - ${storage_path}/clickhouse_node_01_log:/var/log/clickhouse-server/ 
      # - ${storage_path}/clickhouse_node_01:/etc/clickhouse-server/config.d
      
  clickhouse_node_02:
    image: yandex/clickhouse-server 
    container_name: clickhouse_node_02
    ports:
      - '8002:8123'
      - '9002:9000'
      - '9182:9181'
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=default
    volumes:
      - ${storage_path}/clickhouse_node_02_log:/var/log/clickhouse-server/ 
      # - ${storage_path}/clickhouse_node_02:/etc/clickhouse-server/config.d
      
  clickhouse_node_03:
    image: yandex/clickhouse-server 
    container_name: clickhouse_node_03
    ports:
      - '8003:8123'
      - '9003:9000'
      - '9183:9181'
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=default
    volumes:
      - ${storage_path}/clickhouse_node_03_log:/var/log/clickhouse-server/ 
      # - ${storage_path}/clickhouse_node_03:/etc/clickhouse-server/config.d
      
  clickhouse_node_04:
    image: yandex/clickhouse-server 
    container_name: clickhouse_node_04
    ports:
      - '8004:8123'
      - '9004:9000'
      - '9184:9181'
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=default
    volumes:
      - ${storage_path}/clickhouse_node_04_log:/var/log/clickhouse-server/ 
      # - ${storage_path}/clickhouse_node_04:/etc/clickhouse-server/config.d
      